# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='logged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
