# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soc_auth', '0002_auto_20170310_2133'),
        ('wall', '0003_auto_20170310_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('root_parent_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc_auth.Authors')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.RemoveField(
            model_name='messages',
            name='level',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='msg_type',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='root_parent_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.Messages'),
        ),
    ]
