# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_auto_20170311_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='root_parent_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='wall.Messages'),
        ),
    ]
